spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ad
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jdbc:
    template:
      query-timeout: 3
mybatis:
#  config-location: classpath:mybatis/mybatis-cofig.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration: #指定mybatis全局配置
    map-underscore-to-camel-case: true